/*
 * 谷仓
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.dromara.threepart.logistics.goodcang.api;

import org.dromara.threepart.logistics.goodcang.client.ApiException;
import org.dromara.threepart.logistics.goodcang.model.GetShippingMethodRequest;
import org.dromara.threepart.logistics.goodcang.model.GetShippingMethodResponse;
import org.dromara.threepart.logistics.goodcang.model.SysBaseInfoResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Disabled
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    /**
     * 获取物流产品
     *
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void publicOpenBaseDataGetShippingMethodPostTest() throws ApiException {
        String appToken = "7013991264f611e98ea200e01b680258";
        String appKey = "1e40adc162c6e98bcf3b00624bed0d99";
        GetShippingMethodRequest getShippingMethodRequest = new GetShippingMethodRequest();
        getShippingMethodRequest.setIsOoh(0);
        GetShippingMethodResponse response = api.publicOpenBaseDataGetShippingMethodPost(appToken, appKey, getShippingMethodRequest);
        System.out.println(response);
    }

    /**
     * 获取业务基础数据信息
     *
     *
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void publicOpenBaseDataSysBaseInfoPostTest() throws ApiException {
        String appToken = "7013991264f611e98ea200e01b680258";
        String appKey = "1e40adc162c6e98bcf3b00624bed0d99";
        SysBaseInfoResponse response = api.publicOpenBaseDataSysBaseInfoPost(appToken, appKey);
        System.out.println(response);
    }

}
