/*
 * 谷仓
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.dromara.threepart.logistics.goodcang.model;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import org.dromara.threepart.logistics.goodcang.client.JSON;

import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * GetShippingMethodRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-05T18:22:56.415562500+08:00[Asia/Shanghai]", comments = "Generator version: 7.13.0")
public class GetShippingMethodRequest extends GoodcnagRequest {
    public static final String SERIALIZED_NAME_IS_OOH = "is_ooh";
    @SerializedName(SERIALIZED_NAME_IS_OOH)
    @javax.annotation.Nullable
    private Integer isOoh;

    public static final String SERIALIZED_NAME_WAREHOUSE_CODE = "warehouseCode";
    @SerializedName(SERIALIZED_NAME_WAREHOUSE_CODE)
    @javax.annotation.Nullable
    private String warehouseCode;

    public GetShippingMethodRequest() {
    }

    public GetShippingMethodRequest isOoh(@javax.annotation.Nullable Integer isOoh) {
        this.isOoh = isOoh;
        return this;
    }

    /**
     * 是否支持户外配送
     *
     * @return isOoh
     */
    @javax.annotation.Nullable
    public Integer getIsOoh() {
        return isOoh;
    }

    public void setIsOoh(@javax.annotation.Nullable Integer isOoh) {
        this.isOoh = isOoh;
    }


    public GetShippingMethodRequest warehouseCode(@javax.annotation.Nullable String warehouseCode) {
        this.warehouseCode = warehouseCode;
        return this;
    }

    /**
     * 尾程仓库代码
     *
     * @return warehouseCode
     */
    @javax.annotation.Nullable
    public String getWarehouseCode() {
        return warehouseCode;
    }

    public void setWarehouseCode(@javax.annotation.Nullable String warehouseCode) {
        this.warehouseCode = warehouseCode;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetShippingMethodRequest getShippingMethodRequest = (GetShippingMethodRequest) o;
        return Objects.equals(this.isOoh, getShippingMethodRequest.isOoh) &&
                Objects.equals(this.warehouseCode, getShippingMethodRequest.warehouseCode);
    }

    @Override
    public int hashCode() {
        return Objects.hash(isOoh, warehouseCode);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class GetShippingMethodRequest {\n");
        sb.append("    isOoh: ").append(toIndentedString(isOoh)).append("\n");
        sb.append("    warehouseCode: ").append(toIndentedString(warehouseCode)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }


    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("is_ooh");
        openapiFields.add("warehouseCode");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to GetShippingMethodRequest
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!GetShippingMethodRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(String.format("The required field(s) %s in GetShippingMethodRequest is not found in the empty JSON string", GetShippingMethodRequest.openapiRequiredFields.toString()));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!GetShippingMethodRequest.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GetShippingMethodRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if ((jsonObj.get("warehouseCode") != null && !jsonObj.get("warehouseCode").isJsonNull()) && !jsonObj.get("warehouseCode").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format("Expected the field `warehouseCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("warehouseCode").toString()));
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!GetShippingMethodRequest.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'GetShippingMethodRequest' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<GetShippingMethodRequest> thisAdapter
                    = gson.getDelegateAdapter(this, TypeToken.get(GetShippingMethodRequest.class));

            return (TypeAdapter<T>) new TypeAdapter<GetShippingMethodRequest>() {
                @Override
                public void write(JsonWriter out, GetShippingMethodRequest value) throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }

                @Override
                public GetShippingMethodRequest read(JsonReader in) throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);
                    validateJsonElement(jsonElement);
                    return thisAdapter.fromJsonTree(jsonElement);
                }

            }.nullSafe();
        }
    }

    /**
     * Create an instance of GetShippingMethodRequest given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of GetShippingMethodRequest
     * @throws IOException if the JSON string is invalid with respect to GetShippingMethodRequest
     */
    public static GetShippingMethodRequest fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, GetShippingMethodRequest.class);
    }

    /**
     * Convert an instance of GetShippingMethodRequest to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

