/*
 * 谷仓
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.dromara.threepart.logistics.goodcang.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.dromara.threepart.logistics.goodcang.client.JSON;

/**
 * GetShippingMethodDataResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-05T18:22:56.415562500+08:00[Asia/Shanghai]", comments = "Generator version: 7.13.0")
public class GetShippingMethodDataResponse {
  public static final String SERIALIZED_NAME_ADDRESS_VALIDATION_ENABLED = "address_validation_enabled";
  @SerializedName(SERIALIZED_NAME_ADDRESS_VALIDATION_ENABLED)
  @javax.annotation.Nonnull
  private Integer addressValidationEnabled;

  public static final String SERIALIZED_NAME_CODE = "code";
  @SerializedName(SERIALIZED_NAME_CODE)
  @javax.annotation.Nullable
  private String code;

  public static final String SERIALIZED_NAME_DELIVERY_TIME_LIST = "delivery_time_list";
  @SerializedName(SERIALIZED_NAME_DELIVERY_TIME_LIST)
  @javax.annotation.Nullable
  private List<String> deliveryTimeList = new ArrayList<>();

  public static final String SERIALIZED_NAME_DISTRIBUTOR_TYPE = "distributor_type";
  @SerializedName(SERIALIZED_NAME_DISTRIBUTOR_TYPE)
  @javax.annotation.Nullable
  private Integer distributorType;

  public static final String SERIALIZED_NAME_INSURANCE_CURRENCY = "insurance_currency";
  @SerializedName(SERIALIZED_NAME_INSURANCE_CURRENCY)
  @javax.annotation.Nullable
  private String insuranceCurrency;

  public static final String SERIALIZED_NAME_INSURANCE_RANGE = "insurance_range";
  @SerializedName(SERIALIZED_NAME_INSURANCE_RANGE)
  @javax.annotation.Nullable
  private String insuranceRange;

  public static final String SERIALIZED_NAME_IS_INSURANCE = "is_insurance";
  @SerializedName(SERIALIZED_NAME_IS_INSURANCE)
  @javax.annotation.Nullable
  private Integer isInsurance;

  public static final String SERIALIZED_NAME_IS_OOH = "is_ooh";
  @SerializedName(SERIALIZED_NAME_IS_OOH)
  @javax.annotation.Nonnull
  private Integer isOoh;

  public static final String SERIALIZED_NAME_IS_OPTIONAL_BOARD = "is_optional_board";
  @SerializedName(SERIALIZED_NAME_IS_OPTIONAL_BOARD)
  @javax.annotation.Nonnull
  private Integer isOptionalBoard;

  public static final String SERIALIZED_NAME_IS_SIGNATURE = "is_signature";
  @SerializedName(SERIALIZED_NAME_IS_SIGNATURE)
  @javax.annotation.Nonnull
  private Integer isSignature;

  public static final String SERIALIZED_NAME_IS_SPECIFY_ARRIVAL_TIME = "is_specify_arrival_time";
  @SerializedName(SERIALIZED_NAME_IS_SPECIFY_ARRIVAL_TIME)
  @javax.annotation.Nullable
  private Integer isSpecifyArrivalTime;

  public static final String SERIALIZED_NAME_IS_TRUCK = "is_truck";
  @SerializedName(SERIALIZED_NAME_IS_TRUCK)
  @javax.annotation.Nonnull
  private Integer isTruck;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_NAME_EN = "name_en";
  @SerializedName(SERIALIZED_NAME_NAME_EN)
  @javax.annotation.Nullable
  private String nameEn;

  public static final String SERIALIZED_NAME_SM_BUSINESS_TYPE = "sm_business_type";
  @SerializedName(SERIALIZED_NAME_SM_BUSINESS_TYPE)
  @javax.annotation.Nullable
  private String smBusinessType;

  public static final String SERIALIZED_NAME_SP_CODE = "sp_code";
  @SerializedName(SERIALIZED_NAME_SP_CODE)
  @javax.annotation.Nonnull
  private String spCode;

  public static final String SERIALIZED_NAME_TRANSPORT_MODE = "transport_mode";
  @SerializedName(SERIALIZED_NAME_TRANSPORT_MODE)
  @javax.annotation.Nullable
  private Integer transportMode;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  @javax.annotation.Nonnull
  private String type;

  public static final String SERIALIZED_NAME_WAREHOUSE_CODE = "warehouse_code";
  @SerializedName(SERIALIZED_NAME_WAREHOUSE_CODE)
  @javax.annotation.Nonnull
  private String warehouseCode;

  public GetShippingMethodDataResponse() {
  }

  public GetShippingMethodDataResponse addressValidationEnabled(@javax.annotation.Nonnull Integer addressValidationEnabled) {
    this.addressValidationEnabled = addressValidationEnabled;
    return this;
  }

  /**
   * 是否支持地址校验
   * @return addressValidationEnabled
   */
  @javax.annotation.Nonnull
  public Integer getAddressValidationEnabled() {
    return addressValidationEnabled;
  }

  public void setAddressValidationEnabled(@javax.annotation.Nonnull Integer addressValidationEnabled) {
    this.addressValidationEnabled = addressValidationEnabled;
  }


  public GetShippingMethodDataResponse code(@javax.annotation.Nullable String code) {
    this.code = code;
    return this;
  }

  /**
   * 物流产品编码，大小写敏感，创建相关单据引用该代码时，请遵从系统提供的代码传入参数值
   * @return code
   */
  @javax.annotation.Nullable
  public String getCode() {
    return code;
  }

  public void setCode(@javax.annotation.Nullable String code) {
    this.code = code;
  }


  public GetShippingMethodDataResponse deliveryTimeList(@javax.annotation.Nullable List<String> deliveryTimeList) {
    this.deliveryTimeList = deliveryTimeList;
    return this;
  }

  public GetShippingMethodDataResponse addDeliveryTimeListItem(String deliveryTimeListItem) {
    if (this.deliveryTimeList == null) {
      this.deliveryTimeList = new ArrayList<>();
    }
    this.deliveryTimeList.add(deliveryTimeListItem);
    return this;
  }

  /**
   * 支持的到货时间段
   * @return deliveryTimeList
   */
  @javax.annotation.Nullable
  public List<String> getDeliveryTimeList() {
    return deliveryTimeList;
  }

  public void setDeliveryTimeList(@javax.annotation.Nullable List<String> deliveryTimeList) {
    this.deliveryTimeList = deliveryTimeList;
  }


  public GetShippingMethodDataResponse distributorType(@javax.annotation.Nullable Integer distributorType) {
    this.distributorType = distributorType;
    return this;
  }

  /**
   * 配送商类型
   * @return distributorType
   */
  @javax.annotation.Nullable
  public Integer getDistributorType() {
    return distributorType;
  }

  public void setDistributorType(@javax.annotation.Nullable Integer distributorType) {
    this.distributorType = distributorType;
  }


  public GetShippingMethodDataResponse insuranceCurrency(@javax.annotation.Nullable String insuranceCurrency) {
    this.insuranceCurrency = insuranceCurrency;
    return this;
  }

  /**
   * 投保金额的币种信息
   * @return insuranceCurrency
   */
  @javax.annotation.Nullable
  public String getInsuranceCurrency() {
    return insuranceCurrency;
  }

  public void setInsuranceCurrency(@javax.annotation.Nullable String insuranceCurrency) {
    this.insuranceCurrency = insuranceCurrency;
  }


  public GetShippingMethodDataResponse insuranceRange(@javax.annotation.Nullable String insuranceRange) {
    this.insuranceRange = insuranceRange;
    return this;
  }

  /**
   * 投保金额范围值
   * @return insuranceRange
   */
  @javax.annotation.Nullable
  public String getInsuranceRange() {
    return insuranceRange;
  }

  public void setInsuranceRange(@javax.annotation.Nullable String insuranceRange) {
    this.insuranceRange = insuranceRange;
  }


  public GetShippingMethodDataResponse isInsurance(@javax.annotation.Nullable Integer isInsurance) {
    this.isInsurance = isInsurance;
    return this;
  }

  /**
   * 保险服务
   * @return isInsurance
   */
  @javax.annotation.Nullable
  public Integer getIsInsurance() {
    return isInsurance;
  }

  public void setIsInsurance(@javax.annotation.Nullable Integer isInsurance) {
    this.isInsurance = isInsurance;
  }


  public GetShippingMethodDataResponse isOoh(@javax.annotation.Nonnull Integer isOoh) {
    this.isOoh = isOoh;
    return this;
  }

  /**
   * 是否支持户外配送 0否 1是
   * @return isOoh
   */
  @javax.annotation.Nonnull
  public Integer getIsOoh() {
    return isOoh;
  }

  public void setIsOoh(@javax.annotation.Nonnull Integer isOoh) {
    this.isOoh = isOoh;
  }


  public GetShippingMethodDataResponse isOptionalBoard(@javax.annotation.Nonnull Integer isOptionalBoard) {
    this.isOptionalBoard = isOptionalBoard;
    return this;
  }

  /**
   * 是否打板 0否 1是
   * @return isOptionalBoard
   */
  @javax.annotation.Nonnull
  public Integer getIsOptionalBoard() {
    return isOptionalBoard;
  }

  public void setIsOptionalBoard(@javax.annotation.Nonnull Integer isOptionalBoard) {
    this.isOptionalBoard = isOptionalBoard;
  }


  public GetShippingMethodDataResponse isSignature(@javax.annotation.Nonnull Integer isSignature) {
    this.isSignature = isSignature;
    return this;
  }

  /**
   * 是否支持签名服务的增值服务
   * @return isSignature
   */
  @javax.annotation.Nonnull
  public Integer getIsSignature() {
    return isSignature;
  }

  public void setIsSignature(@javax.annotation.Nonnull Integer isSignature) {
    this.isSignature = isSignature;
  }


  public GetShippingMethodDataResponse isSpecifyArrivalTime(@javax.annotation.Nullable Integer isSpecifyArrivalTime) {
    this.isSpecifyArrivalTime = isSpecifyArrivalTime;
    return this;
  }

  /**
   * 是否指定到货时间
   * @return isSpecifyArrivalTime
   */
  @javax.annotation.Nullable
  public Integer getIsSpecifyArrivalTime() {
    return isSpecifyArrivalTime;
  }

  public void setIsSpecifyArrivalTime(@javax.annotation.Nullable Integer isSpecifyArrivalTime) {
    this.isSpecifyArrivalTime = isSpecifyArrivalTime;
  }


  public GetShippingMethodDataResponse isTruck(@javax.annotation.Nonnull Integer isTruck) {
    this.isTruck = isTruck;
    return this;
  }

  /**
   * 是否卡派渠道
   * @return isTruck
   */
  @javax.annotation.Nonnull
  public Integer getIsTruck() {
    return isTruck;
  }

  public void setIsTruck(@javax.annotation.Nonnull Integer isTruck) {
    this.isTruck = isTruck;
  }


  public GetShippingMethodDataResponse name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * 物流产品中文名称
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public GetShippingMethodDataResponse nameEn(@javax.annotation.Nullable String nameEn) {
    this.nameEn = nameEn;
    return this;
  }

  /**
   * 物流产品英文名称
   * @return nameEn
   */
  @javax.annotation.Nullable
  public String getNameEn() {
    return nameEn;
  }

  public void setNameEn(@javax.annotation.Nullable String nameEn) {
    this.nameEn = nameEn;
  }


  public GetShippingMethodDataResponse smBusinessType(@javax.annotation.Nullable String smBusinessType) {
    this.smBusinessType = smBusinessType;
    return this;
  }

  /**
   * 业务类型（旧的业务类型，不推荐对接）
   * @return smBusinessType
   */
  @javax.annotation.Nullable
  public String getSmBusinessType() {
    return smBusinessType;
  }

  public void setSmBusinessType(@javax.annotation.Nullable String smBusinessType) {
    this.smBusinessType = smBusinessType;
  }


  public GetShippingMethodDataResponse spCode(@javax.annotation.Nonnull String spCode) {
    this.spCode = spCode;
    return this;
  }

  /**
   * 服务商代码
   * @return spCode
   */
  @javax.annotation.Nonnull
  public String getSpCode() {
    return spCode;
  }

  public void setSpCode(@javax.annotation.Nonnull String spCode) {
    this.spCode = spCode;
  }


  public GetShippingMethodDataResponse transportMode(@javax.annotation.Nullable Integer transportMode) {
    this.transportMode = transportMode;
    return this;
  }

  /**
   * 运输方式
   * @return transportMode
   */
  @javax.annotation.Nullable
  public Integer getTransportMode() {
    return transportMode;
  }

  public void setTransportMode(@javax.annotation.Nullable Integer transportMode) {
    this.transportMode = transportMode;
  }


  public GetShippingMethodDataResponse type(@javax.annotation.Nonnull String type) {
    this.type = type;
    return this;
  }

  /**
   * 物流产品类型
   * @return type
   */
  @javax.annotation.Nonnull
  public String getType() {
    return type;
  }

  public void setType(@javax.annotation.Nonnull String type) {
    this.type = type;
  }


  public GetShippingMethodDataResponse warehouseCode(@javax.annotation.Nonnull String warehouseCode) {
    this.warehouseCode = warehouseCode;
    return this;
  }

  /**
   * 仓库代码
   * @return warehouseCode
   */
  @javax.annotation.Nonnull
  public String getWarehouseCode() {
    return warehouseCode;
  }

  public void setWarehouseCode(@javax.annotation.Nonnull String warehouseCode) {
    this.warehouseCode = warehouseCode;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetShippingMethodDataResponse getShippingMethodDataResponse = (GetShippingMethodDataResponse) o;
    return Objects.equals(this.addressValidationEnabled, getShippingMethodDataResponse.addressValidationEnabled) &&
        Objects.equals(this.code, getShippingMethodDataResponse.code) &&
        Objects.equals(this.deliveryTimeList, getShippingMethodDataResponse.deliveryTimeList) &&
        Objects.equals(this.distributorType, getShippingMethodDataResponse.distributorType) &&
        Objects.equals(this.insuranceCurrency, getShippingMethodDataResponse.insuranceCurrency) &&
        Objects.equals(this.insuranceRange, getShippingMethodDataResponse.insuranceRange) &&
        Objects.equals(this.isInsurance, getShippingMethodDataResponse.isInsurance) &&
        Objects.equals(this.isOoh, getShippingMethodDataResponse.isOoh) &&
        Objects.equals(this.isOptionalBoard, getShippingMethodDataResponse.isOptionalBoard) &&
        Objects.equals(this.isSignature, getShippingMethodDataResponse.isSignature) &&
        Objects.equals(this.isSpecifyArrivalTime, getShippingMethodDataResponse.isSpecifyArrivalTime) &&
        Objects.equals(this.isTruck, getShippingMethodDataResponse.isTruck) &&
        Objects.equals(this.name, getShippingMethodDataResponse.name) &&
        Objects.equals(this.nameEn, getShippingMethodDataResponse.nameEn) &&
        Objects.equals(this.smBusinessType, getShippingMethodDataResponse.smBusinessType) &&
        Objects.equals(this.spCode, getShippingMethodDataResponse.spCode) &&
        Objects.equals(this.transportMode, getShippingMethodDataResponse.transportMode) &&
        Objects.equals(this.type, getShippingMethodDataResponse.type) &&
        Objects.equals(this.warehouseCode, getShippingMethodDataResponse.warehouseCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(addressValidationEnabled, code, deliveryTimeList, distributorType, insuranceCurrency, insuranceRange, isInsurance, isOoh, isOptionalBoard, isSignature, isSpecifyArrivalTime, isTruck, name, nameEn, smBusinessType, spCode, transportMode, type, warehouseCode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetShippingMethodDataResponse {\n");
    sb.append("    addressValidationEnabled: ").append(toIndentedString(addressValidationEnabled)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    deliveryTimeList: ").append(toIndentedString(deliveryTimeList)).append("\n");
    sb.append("    distributorType: ").append(toIndentedString(distributorType)).append("\n");
    sb.append("    insuranceCurrency: ").append(toIndentedString(insuranceCurrency)).append("\n");
    sb.append("    insuranceRange: ").append(toIndentedString(insuranceRange)).append("\n");
    sb.append("    isInsurance: ").append(toIndentedString(isInsurance)).append("\n");
    sb.append("    isOoh: ").append(toIndentedString(isOoh)).append("\n");
    sb.append("    isOptionalBoard: ").append(toIndentedString(isOptionalBoard)).append("\n");
    sb.append("    isSignature: ").append(toIndentedString(isSignature)).append("\n");
    sb.append("    isSpecifyArrivalTime: ").append(toIndentedString(isSpecifyArrivalTime)).append("\n");
    sb.append("    isTruck: ").append(toIndentedString(isTruck)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    nameEn: ").append(toIndentedString(nameEn)).append("\n");
    sb.append("    smBusinessType: ").append(toIndentedString(smBusinessType)).append("\n");
    sb.append("    spCode: ").append(toIndentedString(spCode)).append("\n");
    sb.append("    transportMode: ").append(toIndentedString(transportMode)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    warehouseCode: ").append(toIndentedString(warehouseCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("address_validation_enabled");
    openapiFields.add("code");
    openapiFields.add("delivery_time_list");
    openapiFields.add("distributor_type");
    openapiFields.add("insurance_currency");
    openapiFields.add("insurance_range");
    openapiFields.add("is_insurance");
    openapiFields.add("is_ooh");
    openapiFields.add("is_optional_board");
    openapiFields.add("is_signature");
    openapiFields.add("is_specify_arrival_time");
    openapiFields.add("is_truck");
    openapiFields.add("name");
    openapiFields.add("name_en");
    openapiFields.add("sm_business_type");
    openapiFields.add("sp_code");
    openapiFields.add("transport_mode");
    openapiFields.add("type");
    openapiFields.add("warehouse_code");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("address_validation_enabled");
    openapiRequiredFields.add("is_ooh");
    openapiRequiredFields.add("is_optional_board");
    openapiRequiredFields.add("is_signature");
    openapiRequiredFields.add("is_truck");
    openapiRequiredFields.add("sp_code");
    openapiRequiredFields.add("type");
    openapiRequiredFields.add("warehouse_code");
  }

}

