/*
 * 谷仓
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.dromara.threepart.logistics.goodcang.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

/**
 * GoodcangResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-05T18:22:56.415562500+08:00[Asia/Shanghai]", comments = "Generator version: 7.13.0")
public class GoodcangResponse {
    public static final String SERIALIZED_NAME_CODE = "code";
    @SerializedName(SERIALIZED_NAME_CODE)
    @javax.annotation.Nonnull
    private Integer code;

    public static final String SERIALIZED_NAME_ASK = "ask";
    @SerializedName(SERIALIZED_NAME_ASK)
    @javax.annotation.Nonnull
    private String ask;

    public static final String SERIALIZED_NAME_MESSAGE = "message";
    @SerializedName(SERIALIZED_NAME_MESSAGE)
    @javax.annotation.Nonnull
    private String message;

    public GoodcangResponse() {
    }

    public GoodcangResponse code(@javax.annotation.Nonnull Integer code) {
        this.code = code;
        return this;
    }

    /**
     * Get code
     *
     * @return code
     */
    @javax.annotation.Nonnull
    public Integer getCode() {
        return code;
    }

    public void setCode(@javax.annotation.Nonnull Integer code) {
        this.code = code;
    }


    public GoodcangResponse ask(@javax.annotation.Nonnull String ask) {
        this.ask = ask;
        return this;
    }

    /**
     * Get ask
     *
     * @return ask
     */
    @javax.annotation.Nonnull
    public String getAsk() {
        return ask;
    }

    public void setAsk(@javax.annotation.Nonnull String ask) {
        this.ask = ask;
    }


    public GoodcangResponse message(@javax.annotation.Nonnull String message) {
        this.message = message;
        return this;
    }

    /**
     * Get message
     *
     * @return message
     */
    @javax.annotation.Nonnull
    public String getMessage() {
        return message;
    }

    public void setMessage(@javax.annotation.Nonnull String message) {
        this.message = message;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GoodcangResponse GoodcangResponse = (GoodcangResponse) o;
        return Objects.equals(this.code, GoodcangResponse.code) &&
                Objects.equals(this.ask, GoodcangResponse.ask) &&
                Objects.equals(this.message, GoodcangResponse.message);
    }

    @Override
    public int hashCode() {
        return Objects.hash(code, ask, message);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class GoodcangResponse {\n");
        sb.append("    code: ").append(toIndentedString(code)).append("\n");
        sb.append("    ask: ").append(toIndentedString(ask)).append("\n");
        sb.append("    message: ").append(toIndentedString(message)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }


}

