/*
 * 谷仓
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.dromara.threepart.logistics.goodcang.model;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import org.dromara.threepart.logistics.goodcang.client.JSON;

import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * GoodcnagRequest
 */
public class GoodcnagRequest {
    public static final String SERIALIZED_NAME_APP_TOKEN = "appToken";
    @SerializedName(SERIALIZED_NAME_APP_TOKEN)
    @javax.annotation.Nullable
    private String appToken;

    public static final String SERIALIZED_NAME_APP_KEY = "appKey";
    @SerializedName(SERIALIZED_NAME_APP_KEY)
    @javax.annotation.Nullable
    private String appKey;

    public GoodcnagRequest() {
    }

    public GoodcnagRequest appToken(@javax.annotation.Nullable String appToken) {
        this.appToken = appToken;
        return this;
    }

    /**
     * 应用令牌
     *
     * @return app-token
     */
    @javax.annotation.Nullable
    public String getAppToken() {
        return appToken;
    }

    public void setAppToken(@javax.annotation.Nullable String appToken) {
        this.appToken = appToken;
    }


    public GoodcnagRequest appKey(@javax.annotation.Nullable String appKey) {
        this.appKey = appKey;
        return this;
    }

    /**
     * 应用密钥
     *
     * @return app-Key
     */
    @javax.annotation.Nullable
    public String getAppKey() {
        return appKey;
    }

    public void setAppKey(@javax.annotation.Nullable String appKey) {
        this.appKey = appKey;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GoodcnagRequest goodcnagRequest = (GoodcnagRequest) o;
        return Objects.equals(this.appToken, goodcnagRequest.appToken) &&
                Objects.equals(this.appKey, goodcnagRequest.appKey);
    }

    @Override
    public int hashCode() {
        return Objects.hash(appToken, appKey);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class GoodcnagRequest {\n");
        sb.append("    appToken: ").append(toIndentedString(appToken)).append("\n");
        sb.append("    appKey: ").append(toIndentedString(appKey)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

