/*
 * 谷仓
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.dromara.threepart.logistics.goodcang.model;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import org.dromara.threepart.logistics.goodcang.client.JSON;

import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * ProductUnitCodeResponse
 */
public class ProductUnitCodeResponse {
  public static final String SERIALIZED_NAME_UNIT_CODE = "unit_code";
  @SerializedName(SERIALIZED_NAME_UNIT_CODE)
  @javax.annotation.Nonnull
  private String unitCode;

  public static final String SERIALIZED_NAME_UNIT_NAME = "unit_name";
  @SerializedName(SERIALIZED_NAME_UNIT_NAME)
  @javax.annotation.Nonnull
  private String unitName;

  public ProductUnitCodeResponse() {
  }

  public ProductUnitCodeResponse unitCode(@javax.annotation.Nonnull String unitCode) {
    this.unitCode = unitCode;
    return this;
  }

  /**
   * 商品成交单位编码
   * @return unitCode
   */
  @javax.annotation.Nonnull
  public String getUnitCode() {
    return unitCode;
  }

  public void setUnitCode(@javax.annotation.Nonnull String unitCode) {
    this.unitCode = unitCode;
  }


  public ProductUnitCodeResponse unitName(@javax.annotation.Nonnull String unitName) {
    this.unitName = unitName;
    return this;
  }

  /**
   * 商品成交单位名称
   * @return unitName
   */
  @javax.annotation.Nonnull
  public String getUnitName() {
    return unitName;
  }

  public void setUnitName(@javax.annotation.Nonnull String unitName) {
    this.unitName = unitName;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductUnitCodeResponse productUnitCodeResponse = (ProductUnitCodeResponse) o;
    return Objects.equals(this.unitCode, productUnitCodeResponse.unitCode) &&
        Objects.equals(this.unitName, productUnitCodeResponse.unitName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(unitCode, unitName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductUnitCodeResponse {\n");
    sb.append("    unitCode: ").append(toIndentedString(unitCode)).append("\n");
    sb.append("    unitName: ").append(toIndentedString(unitName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("unit_code");
    openapiFields.add("unit_name");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("unit_code");
    openapiRequiredFields.add("unit_name");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ProductUnitCodeResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ProductUnitCodeResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ProductUnitCodeResponse is not found in the empty JSON string", ProductUnitCodeResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ProductUnitCodeResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ProductUnitCodeResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ProductUnitCodeResponse.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("unit_code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `unit_code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("unit_code").toString()));
      }
      if (!jsonObj.get("unit_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `unit_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("unit_name").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ProductUnitCodeResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ProductUnitCodeResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ProductUnitCodeResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ProductUnitCodeResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<ProductUnitCodeResponse>() {
           @Override
           public void write(JsonWriter out, ProductUnitCodeResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ProductUnitCodeResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ProductUnitCodeResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ProductUnitCodeResponse
   * @throws IOException if the JSON string is invalid with respect to ProductUnitCodeResponse
   */
  public static ProductUnitCodeResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ProductUnitCodeResponse.class);
  }

  /**
   * Convert an instance of ProductUnitCodeResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

