/*
 * 谷仓
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.dromara.threepart.logistics.goodcang.model;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import org.dromara.threepart.logistics.goodcang.client.JSON;

import java.io.IOException;
import java.util.*;

/**
 * SysBaseInfoResponseData
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-05T19:29:12.947783300+08:00[Asia/Shanghai]", comments = "Generator version: 7.13.0")
public class SysBaseInfoResponseData {
  public static final String SERIALIZED_NAME_PRODUCT_UNIT_CODE_LIST = "product_unit_code_list";
  @SerializedName(SERIALIZED_NAME_PRODUCT_UNIT_CODE_LIST)
  @javax.annotation.Nonnull
  private List<ProductUnitCodeResponse> productUnitCodeList = new ArrayList<>();

  public static final String SERIALIZED_NAME_PRODUCT_UN_CODE_LIST = "product_un_code_list";
  @SerializedName(SERIALIZED_NAME_PRODUCT_UN_CODE_LIST)
  @javax.annotation.Nonnull
  private List<ProductUnCodeResponse> productUnCodeList = new ArrayList<>();

  public SysBaseInfoResponseData() {
  }

  public SysBaseInfoResponseData productUnitCodeList(@javax.annotation.Nonnull List<ProductUnitCodeResponse> productUnitCodeList) {
    this.productUnitCodeList = productUnitCodeList;
    return this;
  }

  public SysBaseInfoResponseData addProductUnitCodeListItem(ProductUnitCodeResponse productUnitCodeListItem) {
    if (this.productUnitCodeList == null) {
      this.productUnitCodeList = new ArrayList<>();
    }
    this.productUnitCodeList.add(productUnitCodeListItem);
    return this;
  }

  /**
   * 商品成交单位列表
   * @return productUnitCodeList
   */
  @javax.annotation.Nonnull
  public List<ProductUnitCodeResponse> getProductUnitCodeList() {
    return productUnitCodeList;
  }

  public void setProductUnitCodeList(@javax.annotation.Nonnull List<ProductUnitCodeResponse> productUnitCodeList) {
    this.productUnitCodeList = productUnitCodeList;
  }


  public SysBaseInfoResponseData productUnCodeList(@javax.annotation.Nonnull List<ProductUnCodeResponse> productUnCodeList) {
    this.productUnCodeList = productUnCodeList;
    return this;
  }

  public SysBaseInfoResponseData addProductUnCodeListItem(ProductUnCodeResponse productUnCodeListItem) {
    if (this.productUnCodeList == null) {
      this.productUnCodeList = new ArrayList<>();
    }
    this.productUnCodeList.add(productUnCodeListItem);
    return this;
  }

  /**
   * 电池UN编码列表
   * @return productUnCodeList
   */
  @javax.annotation.Nonnull
  public List<ProductUnCodeResponse> getProductUnCodeList() {
    return productUnCodeList;
  }

  public void setProductUnCodeList(@javax.annotation.Nonnull List<ProductUnCodeResponse> productUnCodeList) {
    this.productUnCodeList = productUnCodeList;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SysBaseInfoResponseData sysBaseInfoResponseData = (SysBaseInfoResponseData) o;
    return Objects.equals(this.productUnitCodeList, sysBaseInfoResponseData.productUnitCodeList) &&
        Objects.equals(this.productUnCodeList, sysBaseInfoResponseData.productUnCodeList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(productUnitCodeList, productUnCodeList);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SysBaseInfoResponseData {\n");
    sb.append("    productUnitCodeList: ").append(toIndentedString(productUnitCodeList)).append("\n");
    sb.append("    productUnCodeList: ").append(toIndentedString(productUnCodeList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("product_unit_code_list");
    openapiFields.add("product_un_code_list");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("product_unit_code_list");
    openapiRequiredFields.add("product_un_code_list");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SysBaseInfoResponseData
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SysBaseInfoResponseData.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SysBaseInfoResponseData is not found in the empty JSON string", SysBaseInfoResponseData.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SysBaseInfoResponseData.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SysBaseInfoResponseData` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : SysBaseInfoResponseData.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the json data is an array
      if (!jsonObj.get("product_unit_code_list").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `product_unit_code_list` to be an array in the JSON string but got `%s`", jsonObj.get("product_unit_code_list").toString()));
      }

      JsonArray jsonArrayproductUnitCodeList = jsonObj.getAsJsonArray("product_unit_code_list");
      // validate the required field `product_unit_code_list` (array)
      for (int i = 0; i < jsonArrayproductUnitCodeList.size(); i++) {
        ProductUnitCodeResponse.validateJsonElement(jsonArrayproductUnitCodeList.get(i));
      };
      // ensure the json data is an array
      if (!jsonObj.get("product_un_code_list").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `product_un_code_list` to be an array in the JSON string but got `%s`", jsonObj.get("product_un_code_list").toString()));
      }

      JsonArray jsonArrayproductUnCodeList = jsonObj.getAsJsonArray("product_un_code_list");
      // validate the required field `product_un_code_list` (array)
      for (int i = 0; i < jsonArrayproductUnCodeList.size(); i++) {
        ProductUnCodeResponse.validateJsonElement(jsonArrayproductUnCodeList.get(i));
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SysBaseInfoResponseData.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SysBaseInfoResponseData' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SysBaseInfoResponseData> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SysBaseInfoResponseData.class));

       return (TypeAdapter<T>) new TypeAdapter<SysBaseInfoResponseData>() {
           @Override
           public void write(JsonWriter out, SysBaseInfoResponseData value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SysBaseInfoResponseData read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SysBaseInfoResponseData given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SysBaseInfoResponseData
   * @throws IOException if the JSON string is invalid with respect to SysBaseInfoResponseData
   */
  public static SysBaseInfoResponseData fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SysBaseInfoResponseData.class);
  }

  /**
   * Convert an instance of SysBaseInfoResponseData to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

