/*
 * 谷仓
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.dromara.threepart.logistics.goodcang.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetShippingMethodDataResponse
 */
public class GetShippingMethodDataResponseTest {
    private final GetShippingMethodDataResponse model = new GetShippingMethodDataResponse();

    /**
     * Model tests for GetShippingMethodDataResponse
     */
    @Test
    public void testGetShippingMethodDataResponse() {
        // TODO: test GetShippingMethodDataResponse
    }

    /**
     * Test the property 'addressValidationEnabled'
     */
    @Test
    public void addressValidationEnabledTest() {
        // TODO: test addressValidationEnabled
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'deliveryTimeList'
     */
    @Test
    public void deliveryTimeListTest() {
        // TODO: test deliveryTimeList
    }

    /**
     * Test the property 'distributorType'
     */
    @Test
    public void distributorTypeTest() {
        // TODO: test distributorType
    }

    /**
     * Test the property 'insuranceCurrency'
     */
    @Test
    public void insuranceCurrencyTest() {
        // TODO: test insuranceCurrency
    }

    /**
     * Test the property 'insuranceRange'
     */
    @Test
    public void insuranceRangeTest() {
        // TODO: test insuranceRange
    }

    /**
     * Test the property 'isInsurance'
     */
    @Test
    public void isInsuranceTest() {
        // TODO: test isInsurance
    }

    /**
     * Test the property 'isOoh'
     */
    @Test
    public void isOohTest() {
        // TODO: test isOoh
    }

    /**
     * Test the property 'isOptionalBoard'
     */
    @Test
    public void isOptionalBoardTest() {
        // TODO: test isOptionalBoard
    }

    /**
     * Test the property 'isSignature'
     */
    @Test
    public void isSignatureTest() {
        // TODO: test isSignature
    }

    /**
     * Test the property 'isSpecifyArrivalTime'
     */
    @Test
    public void isSpecifyArrivalTimeTest() {
        // TODO: test isSpecifyArrivalTime
    }

    /**
     * Test the property 'isTruck'
     */
    @Test
    public void isTruckTest() {
        // TODO: test isTruck
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'nameEn'
     */
    @Test
    public void nameEnTest() {
        // TODO: test nameEn
    }

    /**
     * Test the property 'smBusinessType'
     */
    @Test
    public void smBusinessTypeTest() {
        // TODO: test smBusinessType
    }

    /**
     * Test the property 'spCode'
     */
    @Test
    public void spCodeTest() {
        // TODO: test spCode
    }

    /**
     * Test the property 'transportMode'
     */
    @Test
    public void transportModeTest() {
        // TODO: test transportMode
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'warehouseCode'
     */
    @Test
    public void warehouseCodeTest() {
        // TODO: test warehouseCode
    }

}
