/*
 * 谷仓
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.dromara.threepart.logistics.goodcang.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetShippingMethodRequest
 */
public class GetShippingMethodRequestTest {
    private final GetShippingMethodRequest model = new GetShippingMethodRequest();

    /**
     * Model tests for GetShippingMethodRequest
     */
    @Test
    public void testGetShippingMethodRequest() {
        // TODO: test GetShippingMethodRequest
    }

    /**
     * Test the property 'isOoh'
     */
    @Test
    public void isOohTest() {
        // TODO: test isOoh
    }

    /**
     * Test the property 'warehouseCode'
     */
    @Test
    public void warehouseCodeTest() {
        // TODO: test warehouseCode
    }

}
