/*
 * 谷仓
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.dromara.threepart.logistics.goodcang.client;


import java.util.Objects;
import java.util.concurrent.atomic.AtomicReference;
import java.util.function.Supplier;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-05T10:16:19.893944300+08:00[Asia/Shanghai]", comments = "Generator version: 7.13.0")
public class Configuration {
    public static final String VERSION = "1.0.0";

    private static final AtomicReference<GoodcangApiClient> defaultApiClient = new AtomicReference<>();
    private static volatile Supplier<GoodcangApiClient> apiClientFactory = GoodcangApiClient::new;

    /**
     * Get the default API client, which would be used when creating API instances without providing an API client.
     *
     * @return Default API client
     */
    public static GoodcangApiClient getDefaultApiClient() {
        GoodcangApiClient client = defaultApiClient.get();
        if (client == null) {
            client = defaultApiClient.updateAndGet(val -> {
                if (val != null) { // changed by another thread
                    return val;
                }
                return apiClientFactory.get();
            });
        }
        return client;
    }

    /**
     * Set the default API client, which would be used when creating API instances without providing an API client.
     *
     * @param goodcangApiClient API client
     */
    public static void setDefaultApiClient(GoodcangApiClient goodcangApiClient) {
        defaultApiClient.set(goodcangApiClient);
    }

    /**
     * set the callback used to create new ApiClient objects
     */
    public static void setApiClientFactory(Supplier<GoodcangApiClient> factory) {
        apiClientFactory = Objects.requireNonNull(factory);
    }

    private Configuration() {
    }
}
