/*
 * 谷仓
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.dromara.threepart.logistics.goodcang.api;

import com.google.gson.reflect.TypeToken;
import org.dromara.threepart.logistics.goodcang.client.*;
import org.dromara.threepart.logistics.goodcang.model.GetShippingMethodRequest;
import org.dromara.threepart.logistics.goodcang.model.GetShippingMethodResponse;
import org.dromara.threepart.logistics.goodcang.model.SysBaseInfoResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class DefaultApi {
    private GoodcangApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public DefaultApi() {
        this(Configuration.getDefaultApiClient());
    }

    public DefaultApi(GoodcangApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public GoodcangApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(GoodcangApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for publicOpenBaseDataGetShippingMethodPost
     *
     * @param appToken                 (optional, default to {{app-token-uat}})
     * @param appKey                   (optional, default to {{app-key-uat}})
     * @param getShippingMethodRequest (optional)
     * @param _callback                Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     * </table>
     */
    public okhttp3.Call publicOpenBaseDataGetShippingMethodPostCall(@javax.annotation.Nullable String appToken, @javax.annotation.Nullable String appKey, @javax.annotation.Nullable GetShippingMethodRequest getShippingMethodRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[]{};

        // Determine Base Path to Use
        if (localCustomBaseUrl != null) {
            basePath = localCustomBaseUrl;
        } else if (localBasePaths.length > 0) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = getShippingMethodRequest;

        // create path and map variables
        String localVarPath = "/public_open/base_data/get_shipping_method";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
                "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
                "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (appToken != null) {
            localVarHeaderParams.put("app-token", localVarApiClient.parameterToString(appToken));
        }


        if (appKey != null) {
            localVarHeaderParams.put("app-key", localVarApiClient.parameterToString(appKey));
        }


        String[] localVarAuthNames = new String[]{};
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call publicOpenBaseDataGetShippingMethodPostValidateBeforeCall(@javax.annotation.Nullable String appToken, @javax.annotation.Nullable String appKey, @javax.annotation.Nullable GetShippingMethodRequest getShippingMethodRequest, final ApiCallback _callback) throws ApiException {
        return publicOpenBaseDataGetShippingMethodPostCall(appToken, appKey, getShippingMethodRequest, _callback);

    }

    /**
     * 获取物流产品
     *
     * @param appToken                 (optional, default to {{app-token-uat}})
     * @param appKey                   (optional, default to {{app-key-uat}})
     * @param getShippingMethodRequest (optional)
     * @return GetShippingMethodResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     * </table>
     */
    public GetShippingMethodResponse publicOpenBaseDataGetShippingMethodPost(@javax.annotation.Nullable String appToken, @javax.annotation.Nullable String appKey, @javax.annotation.Nullable GetShippingMethodRequest getShippingMethodRequest) throws ApiException {
        ApiResponse<GetShippingMethodResponse> localVarResp = publicOpenBaseDataGetShippingMethodPostWithHttpInfo(appToken, appKey, getShippingMethodRequest);
        return localVarResp.getData();
    }

    /**
     * 获取物流产品
     *
     * @param appToken                 (optional, default to {{app-token-uat}})
     * @param appKey                   (optional, default to {{app-key-uat}})
     * @param getShippingMethodRequest (optional)
     * @return ApiResponse&lt;GetShippingMethodResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     * </table>
     */
    public ApiResponse<GetShippingMethodResponse> publicOpenBaseDataGetShippingMethodPostWithHttpInfo(@javax.annotation.Nullable String appToken, @javax.annotation.Nullable String appKey, @javax.annotation.Nullable GetShippingMethodRequest getShippingMethodRequest) throws ApiException {
        okhttp3.Call localVarCall = publicOpenBaseDataGetShippingMethodPostValidateBeforeCall(appToken, appKey, getShippingMethodRequest, null);
        Type localVarReturnType = new TypeToken<GetShippingMethodResponse>() {
        }.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * 获取物流产品 (asynchronously)
     *
     * @param appToken                 (optional, default to {{app-token-uat}})
     * @param appKey                   (optional, default to {{app-key-uat}})
     * @param getShippingMethodRequest (optional)
     * @param _callback                The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     * </table>
     */
    public okhttp3.Call publicOpenBaseDataGetShippingMethodPostAsync(@javax.annotation.Nullable String appToken, @javax.annotation.Nullable String appKey, @javax.annotation.Nullable GetShippingMethodRequest getShippingMethodRequest, final ApiCallback<GetShippingMethodResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = publicOpenBaseDataGetShippingMethodPostValidateBeforeCall(appToken, appKey, getShippingMethodRequest, _callback);
        Type localVarReturnType = new TypeToken<GetShippingMethodResponse>() {
        }.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    /**
     * Build call for publicOpenBaseDataSysBaseInfoPost
     *
     * @param appToken  (optional, default to {{app-token-uat}})
     * @param appKey    (optional, default to {{app-key-uat}})
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     * </table>
     */
    public okhttp3.Call publicOpenBaseDataSysBaseInfoPostCall(@javax.annotation.Nullable String appToken, @javax.annotation.Nullable String appKey, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[]{};

        // Determine Base Path to Use
        if (localCustomBaseUrl != null) {
            basePath = localCustomBaseUrl;
        } else if (localBasePaths.length > 0) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/public_open/base_data/sys_base_info";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
                "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (appToken != null) {
            localVarHeaderParams.put("app-token", localVarApiClient.parameterToString(appToken));
        }


        if (appKey != null) {
            localVarHeaderParams.put("app-key", localVarApiClient.parameterToString(appKey));
        }


        String[] localVarAuthNames = new String[]{};
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call publicOpenBaseDataSysBaseInfoPostValidateBeforeCall(@javax.annotation.Nullable String appToken, @javax.annotation.Nullable String appKey, final ApiCallback _callback) throws ApiException {
        return publicOpenBaseDataSysBaseInfoPostCall(appToken, appKey, _callback);

    }

    /**
     * 获取业务基础数据信息
     *
     * @param appToken (optional, default to {{app-token-uat}})
     * @param appKey   (optional, default to {{app-key-uat}})
     * @return SysBaseInfoResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     * </table>
     */
    public SysBaseInfoResponse publicOpenBaseDataSysBaseInfoPost(@javax.annotation.Nullable String appToken, @javax.annotation.Nullable String appKey) throws ApiException {
        ApiResponse<SysBaseInfoResponse> localVarResp = publicOpenBaseDataSysBaseInfoPostWithHttpInfo(appToken, appKey);
        return localVarResp.getData();
    }

    /**
     * 获取业务基础数据信息
     *
     * @param appToken (optional, default to {{app-token-uat}})
     * @param appKey   (optional, default to {{app-key-uat}})
     * @return ApiResponse&lt;SysBaseInfoResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     * </table>
     */
    public ApiResponse<SysBaseInfoResponse> publicOpenBaseDataSysBaseInfoPostWithHttpInfo(@javax.annotation.Nullable String appToken, @javax.annotation.Nullable String appKey) throws ApiException {
        okhttp3.Call localVarCall = publicOpenBaseDataSysBaseInfoPostValidateBeforeCall(appToken, appKey, null);
        Type localVarReturnType = new TypeToken<SysBaseInfoResponse>() {
        }.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * 获取业务基础数据信息 (asynchronously)
     *
     * @param appToken  (optional, default to {{app-token-uat}})
     * @param appKey    (optional, default to {{app-key-uat}})
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     * </table>
     */
    public okhttp3.Call publicOpenBaseDataSysBaseInfoPostAsync(@javax.annotation.Nullable String appToken, @javax.annotation.Nullable String appKey, final ApiCallback<SysBaseInfoResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = publicOpenBaseDataSysBaseInfoPostValidateBeforeCall(appToken, appKey, _callback);
        Type localVarReturnType = new TypeToken<SysBaseInfoResponse>() {
        }.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public static class Builder {
        private String endpoint;

        public Builder endpoint(String endpoint) {
            this.endpoint = endpoint;
            return this;
        }

        public DefaultApi build() {
            DefaultApi api = new DefaultApi(new GoodcangApiClient()
                    .setBasePath(endpoint));
            api.setCustomBaseUrl(endpoint);
            return api;
        }
    }

}
